[project]
name = "battery-health"
version = "1.0"
dependencies = [
    "polars==1.37.1", 
    "fastapi[standard]==0.128.0"
    ]

[project.optional-dependencies]
dev = [
    "black==26.1.0",
    "pytest==9.0.2"
]
analytics = [
    "jupyterlab==4.5.3",
    "seaborn==0.13.2",
    "matplotlib==3.10.8"
    
    ]

[tool.setuptools]
py-modules = ['data', 'backend', 'frontend', 'analytics']

[tool.ruff.lint]
ignore = ['E402']